#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanThuocTay
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLY_NHATHUOCTAY")]
	public partial class QuanLiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHITIETHOADON_BAN(CHITIETHOADON_BAN instance);
    partial void UpdateCHITIETHOADON_BAN(CHITIETHOADON_BAN instance);
    partial void DeleteCHITIETHOADON_BAN(CHITIETHOADON_BAN instance);
    partial void InsertCHITIETHOADON_NHAP(CHITIETHOADON_NHAP instance);
    partial void UpdateCHITIETHOADON_NHAP(CHITIETHOADON_NHAP instance);
    partial void DeleteCHITIETHOADON_NHAP(CHITIETHOADON_NHAP instance);
    partial void InsertHOADON_BAN(HOADON_BAN instance);
    partial void UpdateHOADON_BAN(HOADON_BAN instance);
    partial void DeleteHOADON_BAN(HOADON_BAN instance);
    partial void InsertHOADON_NHAP(HOADON_NHAP instance);
    partial void UpdateHOADON_NHAP(HOADON_NHAP instance);
    partial void DeleteHOADON_NHAP(HOADON_NHAP instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAIBENH(LOAIBENH instance);
    partial void UpdateLOAIBENH(LOAIBENH instance);
    partial void DeleteLOAIBENH(LOAIBENH instance);
    partial void InsertLOAITHUOC(LOAITHUOC instance);
    partial void UpdateLOAITHUOC(LOAITHUOC instance);
    partial void DeleteLOAITHUOC(LOAITHUOC instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertNUOCSANXUAT(NUOCSANXUAT instance);
    partial void UpdateNUOCSANXUAT(NUOCSANXUAT instance);
    partial void DeleteNUOCSANXUAT(NUOCSANXUAT instance);
    partial void InsertTHUOC(THUOC instance);
    partial void UpdateTHUOC(THUOC instance);
    partial void DeleteTHUOC(THUOC instance);
    #endregion
		
		public QuanLiDataContext() : 
				base(global::BanThuocTay.Properties.Settings.Default.QUANLY_NHATHUOCTAYConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHITIETHOADON_BAN> CHITIETHOADON_BANs
		{
			get
			{
				return this.GetTable<CHITIETHOADON_BAN>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETHOADON_NHAP> CHITIETHOADON_NHAPs
		{
			get
			{
				return this.GetTable<CHITIETHOADON_NHAP>();
			}
		}
		
		public System.Data.Linq.Table<HOADON_BAN> HOADON_BANs
		{
			get
			{
				return this.GetTable<HOADON_BAN>();
			}
		}
		
		public System.Data.Linq.Table<HOADON_NHAP> HOADON_NHAPs
		{
			get
			{
				return this.GetTable<HOADON_NHAP>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAIBENH> LOAIBENHs
		{
			get
			{
				return this.GetTable<LOAIBENH>();
			}
		}
		
		public System.Data.Linq.Table<LOAITHUOC> LOAITHUOCs
		{
			get
			{
				return this.GetTable<LOAITHUOC>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<NUOCSANXUAT> NUOCSANXUATs
		{
			get
			{
				return this.GetTable<NUOCSANXUAT>();
			}
		}
		
		public System.Data.Linq.Table<THUOC> THUOCs
		{
			get
			{
				return this.GetTable<THUOC>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHOADON_BAN")]
	public partial class CHITIETHOADON_BAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHDB;
		
		private string _MATHUOC;
		
		private string _DVT;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntityRef<HOADON_BAN> _HOADON_BAN;
		
		private EntityRef<THUOC> _THUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDBChanging(string value);
    partial void OnMAHDBChanged();
    partial void OnMATHUOCChanging(string value);
    partial void OnMATHUOCChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public CHITIETHOADON_BAN()
		{
			this._HOADON_BAN = default(EntityRef<HOADON_BAN>);
			this._THUOC = default(EntityRef<THUOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDB", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHDB
		{
			get
			{
				return this._MAHDB;
			}
			set
			{
				if ((this._MAHDB != value))
				{
					if (this._HOADON_BAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHDBChanging(value);
					this.SendPropertyChanging();
					this._MAHDB = value;
					this.SendPropertyChanged("MAHDB");
					this.OnMAHDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUOC", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUOC
		{
			get
			{
				return this._MATHUOC;
			}
			set
			{
				if ((this._MATHUOC != value))
				{
					if (this._THUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHUOCChanging(value);
					this.SendPropertyChanging();
					this._MATHUOC = value;
					this.SendPropertyChanged("MATHUOC");
					this.OnMATHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(30)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_BAN_CHITIETHOADON_BAN", Storage="_HOADON_BAN", ThisKey="MAHDB", OtherKey="MAHDB", IsForeignKey=true)]
		public HOADON_BAN HOADON_BAN
		{
			get
			{
				return this._HOADON_BAN.Entity;
			}
			set
			{
				HOADON_BAN previousValue = this._HOADON_BAN.Entity;
				if (((previousValue != value) 
							|| (this._HOADON_BAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON_BAN.Entity = null;
						previousValue.CHITIETHOADON_BANs.Remove(this);
					}
					this._HOADON_BAN.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADON_BANs.Add(this);
						this._MAHDB = value.MAHDB;
					}
					else
					{
						this._MAHDB = default(string);
					}
					this.SendPropertyChanged("HOADON_BAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUOC_CHITIETHOADON_BAN", Storage="_THUOC", ThisKey="MATHUOC", OtherKey="MATHUOC", IsForeignKey=true)]
		public THUOC THUOC
		{
			get
			{
				return this._THUOC.Entity;
			}
			set
			{
				THUOC previousValue = this._THUOC.Entity;
				if (((previousValue != value) 
							|| (this._THUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUOC.Entity = null;
						previousValue.CHITIETHOADON_BANs.Remove(this);
					}
					this._THUOC.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADON_BANs.Add(this);
						this._MATHUOC = value.MATHUOC;
					}
					else
					{
						this._MATHUOC = default(string);
					}
					this.SendPropertyChanged("THUOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETHOADON_NHAP")]
	public partial class CHITIETHOADON_NHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHDN;
		
		private string _MATHUOC;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntityRef<HOADON_NHAP> _HOADON_NHAP;
		
		private EntityRef<THUOC> _THUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDNChanging(string value);
    partial void OnMAHDNChanged();
    partial void OnMATHUOCChanging(string value);
    partial void OnMATHUOCChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public CHITIETHOADON_NHAP()
		{
			this._HOADON_NHAP = default(EntityRef<HOADON_NHAP>);
			this._THUOC = default(EntityRef<THUOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDN", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHDN
		{
			get
			{
				return this._MAHDN;
			}
			set
			{
				if ((this._MAHDN != value))
				{
					if (this._HOADON_NHAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAHDNChanging(value);
					this.SendPropertyChanging();
					this._MAHDN = value;
					this.SendPropertyChanged("MAHDN");
					this.OnMAHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUOC", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUOC
		{
			get
			{
				return this._MATHUOC;
			}
			set
			{
				if ((this._MATHUOC != value))
				{
					if (this._THUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHUOCChanging(value);
					this.SendPropertyChanging();
					this._MATHUOC = value;
					this.SendPropertyChanged("MATHUOC");
					this.OnMATHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_NHAP_CHITIETHOADON_NHAP", Storage="_HOADON_NHAP", ThisKey="MAHDN", OtherKey="MAHDN", IsForeignKey=true)]
		public HOADON_NHAP HOADON_NHAP
		{
			get
			{
				return this._HOADON_NHAP.Entity;
			}
			set
			{
				HOADON_NHAP previousValue = this._HOADON_NHAP.Entity;
				if (((previousValue != value) 
							|| (this._HOADON_NHAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON_NHAP.Entity = null;
						previousValue.CHITIETHOADON_NHAPs.Remove(this);
					}
					this._HOADON_NHAP.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADON_NHAPs.Add(this);
						this._MAHDN = value.MAHDN;
					}
					else
					{
						this._MAHDN = default(string);
					}
					this.SendPropertyChanged("HOADON_NHAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUOC_CHITIETHOADON_NHAP", Storage="_THUOC", ThisKey="MATHUOC", OtherKey="MATHUOC", IsForeignKey=true)]
		public THUOC THUOC
		{
			get
			{
				return this._THUOC.Entity;
			}
			set
			{
				THUOC previousValue = this._THUOC.Entity;
				if (((previousValue != value) 
							|| (this._THUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THUOC.Entity = null;
						previousValue.CHITIETHOADON_NHAPs.Remove(this);
					}
					this._THUOC.Entity = value;
					if ((value != null))
					{
						value.CHITIETHOADON_NHAPs.Add(this);
						this._MATHUOC = value.MATHUOC;
					}
					else
					{
						this._MATHUOC = default(string);
					}
					this.SendPropertyChanged("THUOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON_BAN")]
	public partial class HOADON_BAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHDB;
		
		private string _MAKH;
		
		private System.Nullable<System.DateTime> _NGAYBAN;
		
		private System.Nullable<decimal> _TONGTIEN;
		
		private string _MANV;
		
		private EntitySet<CHITIETHOADON_BAN> _CHITIETHOADON_BANs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDBChanging(string value);
    partial void OnMAHDBChanged();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnNGAYBANChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYBANChanged();
    partial void OnTONGTIENChanging(System.Nullable<decimal> value);
    partial void OnTONGTIENChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    #endregion
		
		public HOADON_BAN()
		{
			this._CHITIETHOADON_BANs = new EntitySet<CHITIETHOADON_BAN>(new Action<CHITIETHOADON_BAN>(this.attach_CHITIETHOADON_BANs), new Action<CHITIETHOADON_BAN>(this.detach_CHITIETHOADON_BANs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDB", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHDB
		{
			get
			{
				return this._MAHDB;
			}
			set
			{
				if ((this._MAHDB != value))
				{
					this.OnMAHDBChanging(value);
					this.SendPropertyChanging();
					this._MAHDB = value;
					this.SendPropertyChanged("MAHDB");
					this.OnMAHDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="Char(10)")]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBAN", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYBAN
		{
			get
			{
				return this._NGAYBAN;
			}
			set
			{
				if ((this._NGAYBAN != value))
				{
					this.OnNGAYBANChanging(value);
					this.SendPropertyChanging();
					this._NGAYBAN = value;
					this.SendPropertyChanged("NGAYBAN");
					this.OnNGAYBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Money")]
		public System.Nullable<decimal> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_BAN_CHITIETHOADON_BAN", Storage="_CHITIETHOADON_BANs", ThisKey="MAHDB", OtherKey="MAHDB")]
		public EntitySet<CHITIETHOADON_BAN> CHITIETHOADON_BANs
		{
			get
			{
				return this._CHITIETHOADON_BANs;
			}
			set
			{
				this._CHITIETHOADON_BANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON_BAN", Storage="_KHACHHANG", ThisKey="MAKH", OtherKey="MAKH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADON_BANs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADON_BANs.Add(this);
						this._MAKH = value.MAKH;
					}
					else
					{
						this._MAKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON_BAN", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADON_BANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADON_BANs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOADON_BANs(CHITIETHOADON_BAN entity)
		{
			this.SendPropertyChanging();
			entity.HOADON_BAN = this;
		}
		
		private void detach_CHITIETHOADON_BANs(CHITIETHOADON_BAN entity)
		{
			this.SendPropertyChanging();
			entity.HOADON_BAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON_NHAP")]
	public partial class HOADON_NHAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAHDN;
		
		private string _MANCC;
		
		private System.Nullable<System.DateTime> _NGAYLAPHD;
		
		private System.Nullable<decimal> _TONGTIEN;
		
		private string _MANV;
		
		private EntitySet<CHITIETHOADON_NHAP> _CHITIETHOADON_NHAPs;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAHDNChanging(string value);
    partial void OnMAHDNChanged();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnNGAYLAPHDChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPHDChanged();
    partial void OnTONGTIENChanging(System.Nullable<decimal> value);
    partial void OnTONGTIENChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    #endregion
		
		public HOADON_NHAP()
		{
			this._CHITIETHOADON_NHAPs = new EntitySet<CHITIETHOADON_NHAP>(new Action<CHITIETHOADON_NHAP>(this.attach_CHITIETHOADON_NHAPs), new Action<CHITIETHOADON_NHAP>(this.detach_CHITIETHOADON_NHAPs));
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHDN", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAHDN
		{
			get
			{
				return this._MAHDN;
			}
			set
			{
				if ((this._MAHDN != value))
				{
					this.OnMAHDNChanging(value);
					this.SendPropertyChanging();
					this._MAHDN = value;
					this.SendPropertyChanged("MAHDN");
					this.OnMAHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="Char(10)")]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAPHD", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAPHD
		{
			get
			{
				return this._NGAYLAPHD;
			}
			set
			{
				if ((this._NGAYLAPHD != value))
				{
					this.OnNGAYLAPHDChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAPHD = value;
					this.SendPropertyChanged("NGAYLAPHD");
					this.OnNGAYLAPHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGTIEN", DbType="Money")]
		public System.Nullable<decimal> TONGTIEN
		{
			get
			{
				return this._TONGTIEN;
			}
			set
			{
				if ((this._TONGTIEN != value))
				{
					this.OnTONGTIENChanging(value);
					this.SendPropertyChanging();
					this._TONGTIEN = value;
					this.SendPropertyChanged("TONGTIEN");
					this.OnTONGTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_NHAP_CHITIETHOADON_NHAP", Storage="_CHITIETHOADON_NHAPs", ThisKey="MAHDN", OtherKey="MAHDN")]
		public EntitySet<CHITIETHOADON_NHAP> CHITIETHOADON_NHAPs
		{
			get
			{
				return this._CHITIETHOADON_NHAPs;
			}
			set
			{
				this._CHITIETHOADON_NHAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_HOADON_NHAP", Storage="_NHACUNGCAP", ThisKey="MANCC", OtherKey="MANCC", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.HOADON_NHAPs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.HOADON_NHAPs.Add(this);
						this._MANCC = value.MANCC;
					}
					else
					{
						this._MANCC = default(string);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON_NHAP", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADON_NHAPs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADON_NHAPs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOADON_NHAPs(CHITIETHOADON_NHAP entity)
		{
			this.SendPropertyChanging();
			entity.HOADON_NHAP = this;
		}
		
		private void detach_CHITIETHOADON_NHAPs(CHITIETHOADON_NHAP entity)
		{
			this.SendPropertyChanging();
			entity.HOADON_NHAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAKH;
		
		private string _HOTENKH;
		
		private System.Nullable<int> _TUOI;
		
		private string _SDT;
		
		private string _DIACHI;
		
		private string _TENBENH;
		
		private string _TIENSUBENH;
		
		private string _MALOAIBENH;
		
		private EntitySet<HOADON_BAN> _HOADON_BANs;
		
		private EntityRef<LOAIBENH> _LOAIBENH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAKHChanging(string value);
    partial void OnMAKHChanged();
    partial void OnHOTENKHChanging(string value);
    partial void OnHOTENKHChanged();
    partial void OnTUOIChanging(System.Nullable<int> value);
    partial void OnTUOIChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnTENBENHChanging(string value);
    partial void OnTENBENHChanged();
    partial void OnTIENSUBENHChanging(string value);
    partial void OnTIENSUBENHChanged();
    partial void OnMALOAIBENHChanging(string value);
    partial void OnMALOAIBENHChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._HOADON_BANs = new EntitySet<HOADON_BAN>(new Action<HOADON_BAN>(this.attach_HOADON_BANs), new Action<HOADON_BAN>(this.detach_HOADON_BANs));
			this._LOAIBENH = default(EntityRef<LOAIBENH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAKH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAKH
		{
			get
			{
				return this._MAKH;
			}
			set
			{
				if ((this._MAKH != value))
				{
					this.OnMAKHChanging(value);
					this.SendPropertyChanging();
					this._MAKH = value;
					this.SendPropertyChanged("MAKH");
					this.OnMAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENKH", DbType="NVarChar(30)")]
		public string HOTENKH
		{
			get
			{
				return this._HOTENKH;
			}
			set
			{
				if ((this._HOTENKH != value))
				{
					this.OnHOTENKHChanging(value);
					this.SendPropertyChanging();
					this._HOTENKH = value;
					this.SendPropertyChanged("HOTENKH");
					this.OnHOTENKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUOI", DbType="Int")]
		public System.Nullable<int> TUOI
		{
			get
			{
				return this._TUOI;
			}
			set
			{
				if ((this._TUOI != value))
				{
					this.OnTUOIChanging(value);
					this.SendPropertyChanging();
					this._TUOI = value;
					this.SendPropertyChanged("TUOI");
					this.OnTUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(30)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENBENH", DbType="NVarChar(30)")]
		public string TENBENH
		{
			get
			{
				return this._TENBENH;
			}
			set
			{
				if ((this._TENBENH != value))
				{
					this.OnTENBENHChanging(value);
					this.SendPropertyChanging();
					this._TENBENH = value;
					this.SendPropertyChanged("TENBENH");
					this.OnTENBENHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIENSUBENH", DbType="NVarChar(30)")]
		public string TIENSUBENH
		{
			get
			{
				return this._TIENSUBENH;
			}
			set
			{
				if ((this._TIENSUBENH != value))
				{
					this.OnTIENSUBENHChanging(value);
					this.SendPropertyChanging();
					this._TIENSUBENH = value;
					this.SendPropertyChanged("TIENSUBENH");
					this.OnTIENSUBENHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIBENH", DbType="Char(10)")]
		public string MALOAIBENH
		{
			get
			{
				return this._MALOAIBENH;
			}
			set
			{
				if ((this._MALOAIBENH != value))
				{
					if (this._LOAIBENH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIBENHChanging(value);
					this.SendPropertyChanging();
					this._MALOAIBENH = value;
					this.SendPropertyChanged("MALOAIBENH");
					this.OnMALOAIBENHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON_BAN", Storage="_HOADON_BANs", ThisKey="MAKH", OtherKey="MAKH")]
		public EntitySet<HOADON_BAN> HOADON_BANs
		{
			get
			{
				return this._HOADON_BANs;
			}
			set
			{
				this._HOADON_BANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBENH_KHACHHANG", Storage="_LOAIBENH", ThisKey="MALOAIBENH", OtherKey="MALOAIBENH", IsForeignKey=true)]
		public LOAIBENH LOAIBENH
		{
			get
			{
				return this._LOAIBENH.Entity;
			}
			set
			{
				LOAIBENH previousValue = this._LOAIBENH.Entity;
				if (((previousValue != value) 
							|| (this._LOAIBENH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIBENH.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._LOAIBENH.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._MALOAIBENH = value.MALOAIBENH;
					}
					else
					{
						this._MALOAIBENH = default(string);
					}
					this.SendPropertyChanged("LOAIBENH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADON_BANs(HOADON_BAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADON_BANs(HOADON_BAN entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIBENH")]
	public partial class LOAIBENH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAIBENH;
		
		private string _TENLOAIBENH;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIBENHChanging(string value);
    partial void OnMALOAIBENHChanged();
    partial void OnTENLOAIBENHChanging(string value);
    partial void OnTENLOAIBENHChanged();
    #endregion
		
		public LOAIBENH()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIBENH", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAIBENH
		{
			get
			{
				return this._MALOAIBENH;
			}
			set
			{
				if ((this._MALOAIBENH != value))
				{
					this.OnMALOAIBENHChanging(value);
					this.SendPropertyChanging();
					this._MALOAIBENH = value;
					this.SendPropertyChanged("MALOAIBENH");
					this.OnMALOAIBENHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAIBENH", DbType="NVarChar(30)")]
		public string TENLOAIBENH
		{
			get
			{
				return this._TENLOAIBENH;
			}
			set
			{
				if ((this._TENLOAIBENH != value))
				{
					this.OnTENLOAIBENHChanging(value);
					this.SendPropertyChanging();
					this._TENLOAIBENH = value;
					this.SendPropertyChanged("TENLOAIBENH");
					this.OnTENLOAIBENHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBENH_KHACHHANG", Storage="_KHACHHANGs", ThisKey="MALOAIBENH", OtherKey="MALOAIBENH")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBENH = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBENH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAITHUOC")]
	public partial class LOAITHUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAITHUOC;
		
		private string _TENLOAITHUOC;
		
		private string _MALOAIBENH;
		
		private EntitySet<NHACUNGCAP> _NHACUNGCAPs;
		
		private EntitySet<THUOC> _THUOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAITHUOCChanging(string value);
    partial void OnMALOAITHUOCChanged();
    partial void OnTENLOAITHUOCChanging(string value);
    partial void OnTENLOAITHUOCChanged();
    partial void OnMALOAIBENHChanging(string value);
    partial void OnMALOAIBENHChanged();
    #endregion
		
		public LOAITHUOC()
		{
			this._NHACUNGCAPs = new EntitySet<NHACUNGCAP>(new Action<NHACUNGCAP>(this.attach_NHACUNGCAPs), new Action<NHACUNGCAP>(this.detach_NHACUNGCAPs));
			this._THUOCs = new EntitySet<THUOC>(new Action<THUOC>(this.attach_THUOCs), new Action<THUOC>(this.detach_THUOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAITHUOC", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAITHUOC
		{
			get
			{
				return this._MALOAITHUOC;
			}
			set
			{
				if ((this._MALOAITHUOC != value))
				{
					this.OnMALOAITHUOCChanging(value);
					this.SendPropertyChanging();
					this._MALOAITHUOC = value;
					this.SendPropertyChanged("MALOAITHUOC");
					this.OnMALOAITHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAITHUOC", DbType="NVarChar(30)")]
		public string TENLOAITHUOC
		{
			get
			{
				return this._TENLOAITHUOC;
			}
			set
			{
				if ((this._TENLOAITHUOC != value))
				{
					this.OnTENLOAITHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENLOAITHUOC = value;
					this.SendPropertyChanged("TENLOAITHUOC");
					this.OnTENLOAITHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIBENH", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MALOAIBENH
		{
			get
			{
				return this._MALOAIBENH;
			}
			set
			{
				if ((this._MALOAIBENH != value))
				{
					this.OnMALOAIBENHChanging(value);
					this.SendPropertyChanging();
					this._MALOAIBENH = value;
					this.SendPropertyChanged("MALOAIBENH");
					this.OnMALOAIBENHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHUOC_NHACUNGCAP", Storage="_NHACUNGCAPs", ThisKey="MALOAITHUOC", OtherKey="MALOAITHUOC")]
		public EntitySet<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this._NHACUNGCAPs;
			}
			set
			{
				this._NHACUNGCAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHUOC_THUOC", Storage="_THUOCs", ThisKey="MALOAITHUOC", OtherKey="MALOAITHUOC")]
		public EntitySet<THUOC> THUOCs
		{
			get
			{
				return this._THUOCs;
			}
			set
			{
				this._THUOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHACUNGCAPs(NHACUNGCAP entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHUOC = this;
		}
		
		private void detach_NHACUNGCAPs(NHACUNGCAP entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHUOC = null;
		}
		
		private void attach_THUOCs(THUOC entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHUOC = this;
		}
		
		private void detach_THUOCs(THUOC entity)
		{
			this.SendPropertyChanging();
			entity.LOAITHUOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANCC;
		
		private string _TENNCC;
		
		private string _HOTLINE;
		
		private string _DIACHI;
		
		private string _MALOAITHUOC;
		
		private EntitySet<HOADON_NHAP> _HOADON_NHAPs;
		
		private EntityRef<LOAITHUOC> _LOAITHUOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANCCChanging(string value);
    partial void OnMANCCChanged();
    partial void OnTENNCCChanging(string value);
    partial void OnTENNCCChanged();
    partial void OnHOTLINEChanging(string value);
    partial void OnHOTLINEChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnMALOAITHUOCChanging(string value);
    partial void OnMALOAITHUOCChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._HOADON_NHAPs = new EntitySet<HOADON_NHAP>(new Action<HOADON_NHAP>(this.attach_HOADON_NHAPs), new Action<HOADON_NHAP>(this.detach_HOADON_NHAPs));
			this._LOAITHUOC = default(EntityRef<LOAITHUOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANCC", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANCC
		{
			get
			{
				return this._MANCC;
			}
			set
			{
				if ((this._MANCC != value))
				{
					this.OnMANCCChanging(value);
					this.SendPropertyChanging();
					this._MANCC = value;
					this.SendPropertyChanged("MANCC");
					this.OnMANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNCC", DbType="NVarChar(30)")]
		public string TENNCC
		{
			get
			{
				return this._TENNCC;
			}
			set
			{
				if ((this._TENNCC != value))
				{
					this.OnTENNCCChanging(value);
					this.SendPropertyChanging();
					this._TENNCC = value;
					this.SendPropertyChanged("TENNCC");
					this.OnTENNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTLINE", DbType="VarChar(10)")]
		public string HOTLINE
		{
			get
			{
				return this._HOTLINE;
			}
			set
			{
				if ((this._HOTLINE != value))
				{
					this.OnHOTLINEChanging(value);
					this.SendPropertyChanging();
					this._HOTLINE = value;
					this.SendPropertyChanged("HOTLINE");
					this.OnHOTLINEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(30)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAITHUOC", DbType="Char(10)")]
		public string MALOAITHUOC
		{
			get
			{
				return this._MALOAITHUOC;
			}
			set
			{
				if ((this._MALOAITHUOC != value))
				{
					if (this._LOAITHUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAITHUOCChanging(value);
					this.SendPropertyChanging();
					this._MALOAITHUOC = value;
					this.SendPropertyChanged("MALOAITHUOC");
					this.OnMALOAITHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_HOADON_NHAP", Storage="_HOADON_NHAPs", ThisKey="MANCC", OtherKey="MANCC")]
		public EntitySet<HOADON_NHAP> HOADON_NHAPs
		{
			get
			{
				return this._HOADON_NHAPs;
			}
			set
			{
				this._HOADON_NHAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHUOC_NHACUNGCAP", Storage="_LOAITHUOC", ThisKey="MALOAITHUOC", OtherKey="MALOAITHUOC", IsForeignKey=true)]
		public LOAITHUOC LOAITHUOC
		{
			get
			{
				return this._LOAITHUOC.Entity;
			}
			set
			{
				LOAITHUOC previousValue = this._LOAITHUOC.Entity;
				if (((previousValue != value) 
							|| (this._LOAITHUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITHUOC.Entity = null;
						previousValue.NHACUNGCAPs.Remove(this);
					}
					this._LOAITHUOC.Entity = value;
					if ((value != null))
					{
						value.NHACUNGCAPs.Add(this);
						this._MALOAITHUOC = value.MALOAITHUOC;
					}
					else
					{
						this._MALOAITHUOC = default(string);
					}
					this.SendPropertyChanged("LOAITHUOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADON_NHAPs(HOADON_NHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_HOADON_NHAPs(HOADON_NHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _HOTENNV;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _GIOITINH;
		
		private System.Nullable<int> _TUOI;
		
		private string _DIACHI;
		
		private string _SDT;
		
		private string _CHUCVU;
		
		private System.Nullable<decimal> _LUONG;
		
		private EntitySet<HOADON_BAN> _HOADON_BANs;
		
		private EntitySet<HOADON_NHAP> _HOADON_NHAPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnHOTENNVChanging(string value);
    partial void OnHOTENNVChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnTUOIChanging(System.Nullable<int> value);
    partial void OnTUOIChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    partial void OnLUONGChanging(System.Nullable<decimal> value);
    partial void OnLUONGChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._HOADON_BANs = new EntitySet<HOADON_BAN>(new Action<HOADON_BAN>(this.attach_HOADON_BANs), new Action<HOADON_BAN>(this.detach_HOADON_BANs));
			this._HOADON_NHAPs = new EntitySet<HOADON_NHAP>(new Action<HOADON_NHAP>(this.attach_HOADON_NHAPs), new Action<HOADON_NHAP>(this.detach_HOADON_NHAPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENNV", DbType="NVarChar(30)")]
		public string HOTENNV
		{
			get
			{
				return this._HOTENNV;
			}
			set
			{
				if ((this._HOTENNV != value))
				{
					this.OnHOTENNVChanging(value);
					this.SendPropertyChanging();
					this._HOTENNV = value;
					this.SendPropertyChanged("HOTENNV");
					this.OnHOTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(10)")]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUOI", DbType="Int")]
		public System.Nullable<int> TUOI
		{
			get
			{
				return this._TUOI;
			}
			set
			{
				if ((this._TUOI != value))
				{
					this.OnTUOIChanging(value);
					this.SendPropertyChanging();
					this._TUOI = value;
					this.SendPropertyChanged("TUOI");
					this.OnTUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(30)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(10)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="NVarChar(20)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LUONG", DbType="Money")]
		public System.Nullable<decimal> LUONG
		{
			get
			{
				return this._LUONG;
			}
			set
			{
				if ((this._LUONG != value))
				{
					this.OnLUONGChanging(value);
					this.SendPropertyChanging();
					this._LUONG = value;
					this.SendPropertyChanged("LUONG");
					this.OnLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON_BAN", Storage="_HOADON_BANs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<HOADON_BAN> HOADON_BANs
		{
			get
			{
				return this._HOADON_BANs;
			}
			set
			{
				this._HOADON_BANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON_NHAP", Storage="_HOADON_NHAPs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<HOADON_NHAP> HOADON_NHAPs
		{
			get
			{
				return this._HOADON_NHAPs;
			}
			set
			{
				this._HOADON_NHAPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADON_BANs(HOADON_BAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADON_BANs(HOADON_BAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_HOADON_NHAPs(HOADON_NHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADON_NHAPs(HOADON_NHAP entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NUOCSANXUAT")]
	public partial class NUOCSANXUAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANSX;
		
		private string _TENNSX;
		
		private EntitySet<THUOC> _THUOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANSXChanging(string value);
    partial void OnMANSXChanged();
    partial void OnTENNSXChanging(string value);
    partial void OnTENNSXChanged();
    #endregion
		
		public NUOCSANXUAT()
		{
			this._THUOCs = new EntitySet<THUOC>(new Action<THUOC>(this.attach_THUOCs), new Action<THUOC>(this.detach_THUOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANSX", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANSX
		{
			get
			{
				return this._MANSX;
			}
			set
			{
				if ((this._MANSX != value))
				{
					this.OnMANSXChanging(value);
					this.SendPropertyChanging();
					this._MANSX = value;
					this.SendPropertyChanged("MANSX");
					this.OnMANSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNSX", DbType="NVarChar(30)")]
		public string TENNSX
		{
			get
			{
				return this._TENNSX;
			}
			set
			{
				if ((this._TENNSX != value))
				{
					this.OnTENNSXChanging(value);
					this.SendPropertyChanging();
					this._TENNSX = value;
					this.SendPropertyChanged("TENNSX");
					this.OnTENNSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NUOCSANXUAT_THUOC", Storage="_THUOCs", ThisKey="MANSX", OtherKey="MANSX")]
		public EntitySet<THUOC> THUOCs
		{
			get
			{
				return this._THUOCs;
			}
			set
			{
				this._THUOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THUOCs(THUOC entity)
		{
			this.SendPropertyChanging();
			entity.NUOCSANXUAT = this;
		}
		
		private void detach_THUOCs(THUOC entity)
		{
			this.SendPropertyChanging();
			entity.NUOCSANXUAT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THUOC")]
	public partial class THUOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATHUOC;
		
		private string _TENTHUOC;
		
		private string _XUATXU;
		
		private string _TACDUNG;
		
		private string _CACHDUNG;
		
		private string _THANTRONG;
		
		private string _TACDUNGPHU;
		
		private System.Nullable<System.DateTime> _NGAYSX;
		
		private System.Nullable<System.DateTime> _HSD;
		
		private string _DVT;
		
		private System.Nullable<decimal> _GIA;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _MALOAITHUOC;
		
		private string _MANSX;
		
		private EntitySet<CHITIETHOADON_BAN> _CHITIETHOADON_BANs;
		
		private EntitySet<CHITIETHOADON_NHAP> _CHITIETHOADON_NHAPs;
		
		private EntityRef<LOAITHUOC> _LOAITHUOC;
		
		private EntityRef<NUOCSANXUAT> _NUOCSANXUAT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHUOCChanging(string value);
    partial void OnMATHUOCChanged();
    partial void OnTENTHUOCChanging(string value);
    partial void OnTENTHUOCChanged();
    partial void OnXUATXUChanging(string value);
    partial void OnXUATXUChanged();
    partial void OnTACDUNGChanging(string value);
    partial void OnTACDUNGChanged();
    partial void OnCACHDUNGChanging(string value);
    partial void OnCACHDUNGChanged();
    partial void OnTHANTRONGChanging(string value);
    partial void OnTHANTRONGChanged();
    partial void OnTACDUNGPHUChanging(string value);
    partial void OnTACDUNGPHUChanged();
    partial void OnNGAYSXChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSXChanged();
    partial void OnHSDChanging(System.Nullable<System.DateTime> value);
    partial void OnHSDChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnGIAChanging(System.Nullable<decimal> value);
    partial void OnGIAChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnMALOAITHUOCChanging(string value);
    partial void OnMALOAITHUOCChanged();
    partial void OnMANSXChanging(string value);
    partial void OnMANSXChanged();
    #endregion
		
		public THUOC()
		{
			this._CHITIETHOADON_BANs = new EntitySet<CHITIETHOADON_BAN>(new Action<CHITIETHOADON_BAN>(this.attach_CHITIETHOADON_BANs), new Action<CHITIETHOADON_BAN>(this.detach_CHITIETHOADON_BANs));
			this._CHITIETHOADON_NHAPs = new EntitySet<CHITIETHOADON_NHAP>(new Action<CHITIETHOADON_NHAP>(this.attach_CHITIETHOADON_NHAPs), new Action<CHITIETHOADON_NHAP>(this.detach_CHITIETHOADON_NHAPs));
			this._LOAITHUOC = default(EntityRef<LOAITHUOC>);
			this._NUOCSANXUAT = default(EntityRef<NUOCSANXUAT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHUOC", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATHUOC
		{
			get
			{
				return this._MATHUOC;
			}
			set
			{
				if ((this._MATHUOC != value))
				{
					this.OnMATHUOCChanging(value);
					this.SendPropertyChanging();
					this._MATHUOC = value;
					this.SendPropertyChanged("MATHUOC");
					this.OnMATHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHUOC", DbType="NVarChar(30)")]
		public string TENTHUOC
		{
			get
			{
				return this._TENTHUOC;
			}
			set
			{
				if ((this._TENTHUOC != value))
				{
					this.OnTENTHUOCChanging(value);
					this.SendPropertyChanging();
					this._TENTHUOC = value;
					this.SendPropertyChanged("TENTHUOC");
					this.OnTENTHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XUATXU", DbType="NVarChar(30)")]
		public string XUATXU
		{
			get
			{
				return this._XUATXU;
			}
			set
			{
				if ((this._XUATXU != value))
				{
					this.OnXUATXUChanging(value);
					this.SendPropertyChanging();
					this._XUATXU = value;
					this.SendPropertyChanged("XUATXU");
					this.OnXUATXUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TACDUNG", DbType="NVarChar(30)")]
		public string TACDUNG
		{
			get
			{
				return this._TACDUNG;
			}
			set
			{
				if ((this._TACDUNG != value))
				{
					this.OnTACDUNGChanging(value);
					this.SendPropertyChanging();
					this._TACDUNG = value;
					this.SendPropertyChanged("TACDUNG");
					this.OnTACDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CACHDUNG", DbType="NVarChar(30)")]
		public string CACHDUNG
		{
			get
			{
				return this._CACHDUNG;
			}
			set
			{
				if ((this._CACHDUNG != value))
				{
					this.OnCACHDUNGChanging(value);
					this.SendPropertyChanging();
					this._CACHDUNG = value;
					this.SendPropertyChanged("CACHDUNG");
					this.OnCACHDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANTRONG", DbType="NVarChar(30)")]
		public string THANTRONG
		{
			get
			{
				return this._THANTRONG;
			}
			set
			{
				if ((this._THANTRONG != value))
				{
					this.OnTHANTRONGChanging(value);
					this.SendPropertyChanging();
					this._THANTRONG = value;
					this.SendPropertyChanged("THANTRONG");
					this.OnTHANTRONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TACDUNGPHU", DbType="NVarChar(30)")]
		public string TACDUNGPHU
		{
			get
			{
				return this._TACDUNGPHU;
			}
			set
			{
				if ((this._TACDUNGPHU != value))
				{
					this.OnTACDUNGPHUChanging(value);
					this.SendPropertyChanging();
					this._TACDUNGPHU = value;
					this.SendPropertyChanged("TACDUNGPHU");
					this.OnTACDUNGPHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSX", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYSX
		{
			get
			{
				return this._NGAYSX;
			}
			set
			{
				if ((this._NGAYSX != value))
				{
					this.OnNGAYSXChanging(value);
					this.SendPropertyChanging();
					this._NGAYSX = value;
					this.SendPropertyChanged("NGAYSX");
					this.OnNGAYSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSD", DbType="Date")]
		public System.Nullable<System.DateTime> HSD
		{
			get
			{
				return this._HSD;
			}
			set
			{
				if ((this._HSD != value))
				{
					this.OnHSDChanging(value);
					this.SendPropertyChanging();
					this._HSD = value;
					this.SendPropertyChanged("HSD");
					this.OnHSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(20)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA", DbType="Money")]
		public System.Nullable<decimal> GIA
		{
			get
			{
				return this._GIA;
			}
			set
			{
				if ((this._GIA != value))
				{
					this.OnGIAChanging(value);
					this.SendPropertyChanging();
					this._GIA = value;
					this.SendPropertyChanged("GIA");
					this.OnGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAITHUOC", DbType="Char(10)")]
		public string MALOAITHUOC
		{
			get
			{
				return this._MALOAITHUOC;
			}
			set
			{
				if ((this._MALOAITHUOC != value))
				{
					if (this._LOAITHUOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAITHUOCChanging(value);
					this.SendPropertyChanging();
					this._MALOAITHUOC = value;
					this.SendPropertyChanged("MALOAITHUOC");
					this.OnMALOAITHUOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANSX", DbType="Char(10)")]
		public string MANSX
		{
			get
			{
				return this._MANSX;
			}
			set
			{
				if ((this._MANSX != value))
				{
					if (this._NUOCSANXUAT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANSXChanging(value);
					this.SendPropertyChanging();
					this._MANSX = value;
					this.SendPropertyChanged("MANSX");
					this.OnMANSXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUOC_CHITIETHOADON_BAN", Storage="_CHITIETHOADON_BANs", ThisKey="MATHUOC", OtherKey="MATHUOC")]
		public EntitySet<CHITIETHOADON_BAN> CHITIETHOADON_BANs
		{
			get
			{
				return this._CHITIETHOADON_BANs;
			}
			set
			{
				this._CHITIETHOADON_BANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THUOC_CHITIETHOADON_NHAP", Storage="_CHITIETHOADON_NHAPs", ThisKey="MATHUOC", OtherKey="MATHUOC")]
		public EntitySet<CHITIETHOADON_NHAP> CHITIETHOADON_NHAPs
		{
			get
			{
				return this._CHITIETHOADON_NHAPs;
			}
			set
			{
				this._CHITIETHOADON_NHAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAITHUOC_THUOC", Storage="_LOAITHUOC", ThisKey="MALOAITHUOC", OtherKey="MALOAITHUOC", IsForeignKey=true)]
		public LOAITHUOC LOAITHUOC
		{
			get
			{
				return this._LOAITHUOC.Entity;
			}
			set
			{
				LOAITHUOC previousValue = this._LOAITHUOC.Entity;
				if (((previousValue != value) 
							|| (this._LOAITHUOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAITHUOC.Entity = null;
						previousValue.THUOCs.Remove(this);
					}
					this._LOAITHUOC.Entity = value;
					if ((value != null))
					{
						value.THUOCs.Add(this);
						this._MALOAITHUOC = value.MALOAITHUOC;
					}
					else
					{
						this._MALOAITHUOC = default(string);
					}
					this.SendPropertyChanged("LOAITHUOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NUOCSANXUAT_THUOC", Storage="_NUOCSANXUAT", ThisKey="MANSX", OtherKey="MANSX", IsForeignKey=true)]
		public NUOCSANXUAT NUOCSANXUAT
		{
			get
			{
				return this._NUOCSANXUAT.Entity;
			}
			set
			{
				NUOCSANXUAT previousValue = this._NUOCSANXUAT.Entity;
				if (((previousValue != value) 
							|| (this._NUOCSANXUAT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NUOCSANXUAT.Entity = null;
						previousValue.THUOCs.Remove(this);
					}
					this._NUOCSANXUAT.Entity = value;
					if ((value != null))
					{
						value.THUOCs.Add(this);
						this._MANSX = value.MANSX;
					}
					else
					{
						this._MANSX = default(string);
					}
					this.SendPropertyChanged("NUOCSANXUAT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETHOADON_BANs(CHITIETHOADON_BAN entity)
		{
			this.SendPropertyChanging();
			entity.THUOC = this;
		}
		
		private void detach_CHITIETHOADON_BANs(CHITIETHOADON_BAN entity)
		{
			this.SendPropertyChanging();
			entity.THUOC = null;
		}
		
		private void attach_CHITIETHOADON_NHAPs(CHITIETHOADON_NHAP entity)
		{
			this.SendPropertyChanging();
			entity.THUOC = this;
		}
		
		private void detach_CHITIETHOADON_NHAPs(CHITIETHOADON_NHAP entity)
		{
			this.SendPropertyChanging();
			entity.THUOC = null;
		}
	}
}
#pragma warning restore 1591
